# --- 1. ENTRY POINT MAHASISWA (Public) ---
<VirtualHost *:80>
    ServerName vocational.info
    ServerAlias www.vocational.info
    ServerAlias vocational.prod
    
    DocumentRoot /var/www/html/public
    
    <Directory /var/www/html/public>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/main_error.log
    CustomLog ${APACHE_LOG_DIR}/main_access.log combined
</VirtualHost>

# --- 2. ENTRY POINT ADMIN (Isolated) ---
<VirtualHost *:80>
    ServerName admin.vocational.info
    ServerAlias admin.vocational.prod
    
    DocumentRoot /var/www/html/admin/public
    
    <Directory /var/www/html/admin/public>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/admin_error.log
    CustomLog ${APACHE_LOG_DIR}/admin_access.log combined
</VirtualHost>
