name: VocaTIonal Continuous Delivery/Deployment Pipeline

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy and Build to Production Server"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            # 0. Pindah ke direktori proyek
            cd ~/Web-VocaTIonal/

            # 1. Pull kode terbaru
            git checkout .
            git pull origin main

            # 3. Pindah ke direktori aplikasi
            cd ~/Web-VocaTIonal/vocational/
            
            # 2. Matikan container yang lama secara total
            docker compose down

            # 3. Delay 5 Detik untuk memastikan container sudah mati sebelum build ulang
            sleep 5
            
            # 4. Rebuild & Restart Container
            docker compose up -d --build
            
            # 5. Delay 5 detik untuk memastikan container sudah berjalan sebelum migrasi
            sleep 5
            
            # 6. Jalankan Migrasi (@/Config/Migration.php)
            docker exec vocational-web php /var/www/html/app/Config/Migration.php

            # 7. Delay 5 detik untuk memastikan migrasi sudah selesai sebelum cache clear
            sleep 5

            # 8. Bersihkan cache (Jika ada)
            docker exec vocational-web php /var/www/html/app/Config/CacheClear.php

            # 9. Cek status container dan modul SSL
            docker ps
            docker exec vocational-web apache2ctl -M | grep ssl