name: Deployment to DigitalOcean

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd ~/Web-VocaTIonal/vocational

            # 0. Reset perubahan lokal (jika ada) untuk menghindari konflik saat pull
            git checkout .
            
            # 1. Pull kode terbaru dari main
            git pull origin main
            
            # 2. Rebuild & Restart Container
            docker compose up -d --build
            
            # 3. Delay 5 detik untuk memastikan container sudah berjalan sebelum migrasi
            sleep 5
            
            # 4. Jalankan Migrasi (@/Config/Migration.php)
            docker exec vocational-web php /var/www/html/app/Config/Migration.php